### ISSUE TITLE
docs: enhance documentation for winopts parameters

### ISSUE THREAD

**Issue by Frestein** [nvzone/showkeys#10]
The current documentation lacks details on `winopts` and other configuration options. It would be better to include these parameters under a "Default Config" section in the README.

Please document the `border`, `style`, and `relative` options for `winopts` in detail, similar to how the `position` parameter is documented.

**Comment by siduck** [comment]
that needs 0 documentation, everyone knows floating windows have the opts from nvim_open_win function, check its docs

**Comment by Frestein** [comment]
Not everyone knows that. I don't need your advice.

**Comment by siduck** [comment]
please read :h nvim_open_win params

**Comment by Frestein** [comment]
Can't you see what I'm writing?

**Comment by siduck** [comment]
stay ignorant then, i dont see why a plugin needs to re-document winopts if its already documented at :h nvim_open_win.  

i added a note for those who dont know about it https://github.com/nvzone/showkeys/commit/a8bcd950e19116f801ed6714fdba0d385cb24f3c

**Comment by Frestein** [comment]
Ignorant? Kekw.

> i added a note for those who dont know about it [a8bcd95](https://github.com/nvzone/showkeys/commit/a8bcd950e19116f801ed6714fdba0d385cb24f3c)

At least something.

**Comment by shirobachi** [comment]
well documented IMHO in here: https://neovim.io/doc/user/api.html#_win_config-functions ;)

**Comment by siduck** [comment]
@shirobachi  the help page is the same thing btw!

**Comment by Frestein** [comment]
You're both so funny. You're trying to explain to me something I already knew at the moment I opened the issue. It was just a friendly advice, but due to the language barrier, they wrote me off as ignorant.
