### ISSUE TITLE
`showkeys` stops working when closing a tab page

### ISSUE THREAD

**Issue by dpetka2001** [nvzone/showkeys#13]
#12 added a feature for `showkeys` to keep working when changing tabpage. 

However, this autocmd https://github.com/nvzone/showkeys/blob/38a5d15ef687da37ef0de3d6944b9eb6830982f3/lua/showkeys/init.lua#L65-L74 closes `showkeys` when closing a tabpage, since the `WinClosed` event triggers when you close a tab page. 

I managed to make it work locally by changing https://github.com/nvzone/showkeys/blob/38a5d15ef687da37ef0de3d6944b9eb6830982f3/lua/showkeys/init.lua#L68 into 
```lua 
if vim.fn.tabpagenr() < 2 and state.win then
```
Not sure if that is the correct way to do it and if it has other side-effects, just wanted to let you know, so that you could look into it and come up with a proper solution. 

I opened this because I believe it's better behavior that `showkeys` keeps working even if you delete a tab page when there are still other tab pages open.

**Comment by siduck** [comment]
that winclosed one is useful, when users press C-w + C-o , then showkeys must be closed too

**Comment by dpetka2001** [comment]
I understand what you're saying. Then maybe you could follow the same approach as for when entering a new tabpage. So, something like that
```lua
api.nvim_create_autocmd("WinClosed", {
  group = augroup,
  callback = function()
    if state.win then
      M.close()
      M.open()
    end
  end,
  buffer = state.buf,
})
```
This way `Showkeys` doesn't stop working and I haven't observed any weird behavior like in #3 that you tried to solve by closing the buffer. I believe it's more intuitive for `Showkeys` to stop working when user has explicitly issued the command `ShowkeysToggle` again.

Please test out the behavior of the code snippet above. I hope I didn't miss any other potential side-effects.
