### ISSUE TITLE
"invalid window id" after :only / ctrl-w o

### ISSUE THREAD

**Issue by justinmk** [nvzone/showkeys#3]
Thank you for this minimal (code/dependencies) yet aesthetic plugin!

I'm seeing an error (both before and after https://github.com/NvChad/showkeys/commit/92741312a05ee5e4de82e77f28a2db197f87fccc ):

```
Error executing vim.schedule lua callback: .../nvim/site/pack/paqs/opt/showkeys/lua/showkeys/utils.lua:58: Invalid window id: 1005                                       
stack traceback:                                                                                                                                                         
        [C]: in function 'nvim_win_set_config'                                                                                                                           
        .../nvim/site/pack/paqs/opt/showkeys/lua/showkeys/utils.lua:58: in function 'update_win_w'                                                                       
        .../nvim/site/pack/paqs/opt/showkeys/lua/showkeys/utils.lua:77: in function 'redraw'                                                                             
        ...e/nvim/site/pack/paqs/opt/showkeys/lua/showkeys/init.lua:34: in function ''                                                                                   
        vim/_editor.lua: in function <vim/_editor.lua:0>     
```

Steps to reproduce:

1. `:ShowkeysToggle`
2. `ctrl-w v` to split window
3. `ctrl-w o` to close all but one windows
4. `ctrl-c` causes above error

**Comment by siduck** [comment]
i get the issue, its cuz many things need to be unset during close. 

![image](https://github.com/user-attachments/assets/cfe74e0e-a3bb-497f-a58d-020aad6c7460)

So all the volt plugins you see are meant to be closed by "q" mapping in the window. Idk if i could handle this better, need to try winclose or bufdelete autocmds :thinking:

**Comment by siduck** [comment]
i didnt know opening splits would trigger winclosed too  , reverted that commit as it caused this #4
 
 edit: nvm i forgot the buffer option in aucmd
