### ISSUE TITLE
Feature Request: option to choose the list of modes to show the keys

### ISSUE THREAD

**Issue by ratheesh** [nvzone/showkeys#5]
Thank you very much for this wonderful plugin.

An option to choose the list of modes to show the keys (or to exclude the modes) would be very nice addition. It will be helpful not show the keys in certain mode like insert mode if the user does not want to show the typed text and want to enable the plugin for other modes.

**Comment by siduck** [comment]
yes, but do know that when you enter excluded modes, the showkeys window will clear previous keys

**Comment by ratheesh** [comment]
I think it should be okay.
